// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/list-cards.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-cards.ts
var COLUMNS = "id, card_name, card_set, card_year, category, rarity, condition_grade, grading_company, grade_numeric, is_authenticated, estimated_value_low, estimated_value_high, analysis_status, created_at";
var list_cards_default = defineTool({
  name: "list_cards",
  title: "List collection cards",
  description: "List cards in the signed-in collector's MyCollectAI collection, optionally filtered by name/set text or category.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Text to match against card name or set."),
    category: z.string().trim().min(1).optional().describe("Category filter, e.g. Pok\xE9mon or Sports."),
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of cards to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("cards").select(COLUMNS).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (category) query = query.ilike("category", `%${category}%`);
    if (search) query = query.or(`card_name.ilike.%${search}%,card_set.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { cards: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-card.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_card_default = defineTool2({
  name: "get_card",
  title: "Get card details",
  description: "Fetch full details for one card in the signed-in collector's collection, including AI analysis, grading info and market comps.",
  inputSchema: {
    card_id: z2.string().uuid().describe("The card's id.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ card_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("cards").select(
      "id, card_name, card_set, card_year, edition, category, rarity, special_features, condition_grade, grading_company, grade_numeric, grading_cert_number, is_authenticated, authenticated_at, estimated_value_low, estimated_value_high, ebay_recent_sales, tcgplayer_price, ai_analysis, analysis_status, notes, paired_raw_card_id, created_at, updated_at"
    ).eq("id", card_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No card found with that id." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { card: data }
    };
  }
});

// src/lib/mcp/tools/collection-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
function midpoint(low, high) {
  const l = typeof low === "number" ? low : null;
  const h = typeof high === "number" ? high : null;
  if (l !== null && h !== null) return (l + h) / 2;
  return l ?? h ?? 0;
}
var collection_summary_default = defineTool3({
  name: "collection_summary",
  title: "Collection summary",
  description: "Summarize the signed-in collector's MyCollectAI portfolio: card count, estimated total value, graded/authenticated counts and a category breakdown.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("cards").select("category, estimated_value_low, estimated_value_high, is_authenticated, grade_numeric");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const byCategory = {};
    let totalValue = 0;
    let authenticated = 0;
    let graded = 0;
    for (const row of rows) {
      const value = midpoint(row.estimated_value_low, row.estimated_value_high);
      totalValue += value;
      if (row.is_authenticated) authenticated += 1;
      if (typeof row.grade_numeric === "number") graded += 1;
      const key = row.category ?? "Uncategorized";
      byCategory[key] ??= { count: 0, value: 0 };
      byCategory[key].count += 1;
      byCategory[key].value += value;
    }
    const summary = {
      totalCards: rows.length,
      estimatedTotalValueUsd: Math.round(totalValue * 100) / 100,
      authenticatedCards: authenticated,
      gradedCards: graded,
      byCategory
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/update-card-notes.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^3.25.76";
var update_card_notes_default = defineTool4({
  name: "update_card_notes",
  title: "Update card notes",
  description: "Set the personal notes on one card in the signed-in collector's collection.",
  inputSchema: {
    card_id: z3.string().uuid().describe("The card's id."),
    notes: z3.string().max(2e3).describe("New notes text. Pass an empty string to clear the notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ card_id, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("cards").update({ notes: notes.length ? notes : null }).eq("id", card_id).eq("user_id", ctx.getUserId()).select("id, card_name, notes").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No card found with that id." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { card: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "irncxwszrawrndsdaqel";
var mcp_default = defineMcp({
  name: "collector-s-insight",
  title: "Collector's Insight",
  version: "0.1.0",
  instructions: "Tools for MyCollectAI, a trading card scanning, grading and valuation app. Use `collection_summary` for portfolio totals, `list_cards` to browse or search the collection, `get_card` for full details including AI grading and market comps, and `update_card_notes` to edit a card's notes. All tools act as the signed-in collector.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [collection_summary_default, list_cards_default, get_card_default, update_card_notes_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
